/**
 * Generates `skill/SKILL.md` from `AGENTS.md`.
 *
 * ONE SOURCE, TWO ARTIFACTS, and that is the whole design decision here. The same teaching now has three possible
 * homes — the codegen's SYSTEM prompt, the package's `AGENTS.md`, and a Skill — and three hand-kept copies of
 * anything drift in three directions. So the Skill is DERIVED: it is `AGENTS.md` with a header, generated by this
 * script and checked in CI.
 *
 * The SYSTEM prompt is deliberately NOT the source, and the reason is not duplication — it is AUDIENCE. It
 * addresses a model running INSIDE the platform: it emits `fab.schema.json` as a channel (eighteen mentions), calls
 * `set_schema`, and has never heard of `@fabappai/sdk` or `createClient`. An agent on somebody's laptop has the
 * opposite situation: the package, the CLI, and files on disk. Copying those instructions across would ship advice
 * that is precise, battle-tested, and wrong for the reader.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// The description is what decides whether the Skill is loaded at all, so it names the artefacts a person will
// actually have in front of them — a `fab.schema.json`, a `@fabappai/sdk` import, a `fabapp` command.
const FRONTMATTER = `---
name: fabapp
description: >-
  Building on Fabapp: the @fabappai/sdk client, the fabapp CLI, and a project's
  fab.schema.json / fab.config.json files. Use when writing or editing an app
  backed by Fabapp — data access rules, canonical model ids, backend functions,
  connectors — or when a Fabapp API call answers 403, 404 or 422.
---
`;

const agents = readFileSync(join(root, "AGENTS.md"), "utf8");
const skill = FRONTMATTER + "\n" + agents;

const out = join(root, "skill", "SKILL.md");
if (process.argv.includes("--check")) {
  const current = (() => { try { return readFileSync(out, "utf8"); } catch { return ""; } })();
  if (current !== skill) {
    console.error("skill/SKILL.md is out of sync with AGENTS.md — run `npm run skill`.");
    process.exit(1);
  }
  console.log("skill: in sync with AGENTS.md");
} else {
  writeFileSync(out, skill);
  console.log(`skill: ${out} gerado a partir de AGENTS.md (${skill.split("\n").length} linhas)`);
}
